void initListe();
int listeVide();
int horsListe();
void enTete();
void enQueue();
void suivant();
void precedent();
int valeurElt();
void modifElt(int v);
void oterElt();
void ajoutDroit(int v);
void ajoutGauche(int v);
